Repository CreateThrive/react-firebase-admin, pull requests merged in 2020-06, with the labels that each got.

#39 Update node version from 8 to 10 and dependencies
  functions/package-lock.json
  functions/package.json
  functions/setupProject.js
  package-lock.json
Labels: dependencies, good first issue

#41 Feature: Facebook Authentication
  database.rules.json
  package-lock.json
  package.json
  src/components/DatePicker/__snapshots__/DatePicker.test.js.snap
  src/components/Layout/__snapshots__/Layout.test.js.snap
  src/components/Navigation/Aside/__snapshots__/Aside.test.js.snap
  src/components/Navigation/NavBar/__snapshots__/NavBar.test.js.snap
  src/components/UserForm/__snapshots__/UserForm.test.js.snap
  src/languages/en.json
  src/languages/es.json
  src/pages/Home/__snapshots__/Home.test.js.snap
  src/pages/Login/Login.module.scss
  src/pages/Login/Login.test.js
  src/pages/Login/__snapshots__/Login.test.js.snap
  src/pages/Login/index.jsx
  src/pages/NotFound/__snapshots__/NotFound.test.js.snap
  src/pages/Profile/ChangePassword/__snapshots__/ChangePassword.test.js.snap
  src/pages/Profile/__snapshots__/Profile.test.js.snap
  src/pages/ResetPassword/__snapshots__/ResetPassword.test.js.snap
  src/pages/Router/PrivateRoute/__snapshots__/PrivateRoute.test.js.snap
  src/pages/Router/__snapshots__/Router.test.js.snap
  src/pages/Section/__snapshots__/Section.test.js.snap
  src/pages/Submenu/__snapshots__/Submenu.test.js.snap
  src/pages/User/__snapshots__/User.test.js.snap
  src/pages/Users/__snapshots__/Users.test.js.snap
  src/state/actions/auth.js
  src/state/reducers/auth/auth.test.js
  src/state/reducers/auth/index.js
Labels: enhancement

#55 Dependabot setup
  .github/dependabot.yml
Labels: enhancement

#73 Dependencies update
  functions/package-lock.json
  functions/package.json
  package-lock.json
  package.json
Labels: dependencies
