Repository CreateThrive/react-firebase-admin, pull requests merged in 2020-08, with the labels that each got.

#117 Update dependencies
  functions/package-lock.json
  functions/package.json
  package-lock.json
  package.json
Labels: dependencies

#125 Hotfix: User locale now persist in local storage
  README.md
  package-lock.json
  package.json
  src/components/LanguageWrapper/index.js
  src/components/Navigation/NavBar/index.jsx
  src/state/reducers/index.js
Labels: enhancement

#127 Fixed pagination in table
  src/components/Table/index.jsx
Labels: bug

#130 Bugfix : Issue for fetching user profile
  src/pages/Profile/index.jsx
Labels: bug

#142 Updated README
  README.md
  package-lock.json
  package.json
Labels: documentation
